version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
      day: "thursday"

  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
      day: "thursday"
