on: push

jobs:
  tests:
    name: Testing with PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
            php: [8.1, 8.2]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-ansi --no-progress

      - name: Execute tests
        run: |
          vendor/bin/pint --test
          vendor/bin/phpunit
